[thor]
server_ip = "127.0.0.1:6969"
remote_packet_queue_cycle_millis = 250
sampling_interval_micros = 50
max_sample_age = 5000

[amd]
core = true
pkg = true

[intel]
pp0 = true
pp1 = true
pkg = true
dram = true
