[package]
name = "thor-local-client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
bincode = "1"
thread-id = "4"
thor-shared = { path = "../shared" }
